FROM dunglas/frankenphp

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN apt-get update && apt-get install -y git unzip && rm -rf /var/lib/apt/lists/*

# required: pdo_sqlite - optional: pdo_mysql redis
RUN install-php-extensions pdo_sqlite pdo_mysql redis

WORKDIR /app

COPY composer.json composer.lock ./
RUN composer install --no-dev --optimize-autoloader --no-interaction

COPY . .

EXPOSE 8000

CMD ["vendor/bin/flowcrafter", "frankenphp:service"]
