FROM dunglas/frankenphp

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN apt-get update && apt-get install -y git unzip && rm -rf /var/lib/apt/lists/*

RUN install-php-extensions {{EXTENSIONS}}

WORKDIR /app

COPY composer.json composer.lock ./
RUN composer install --no-dev --no-interaction

COPY . .

EXPOSE 8000
