---
title: flow.workflow.v1 - /workflow/1
theme: neo
---
stateDiagram-v2
[*]-->Tests\MockClass\StepMock: Tests\MockClass\MessageInitMock
Tests\MockClass\StepMock-->Tests\MockClass\NextStepMock: Tests\MockClass\MessageDataMock
Tests\MockClass\StepMock-->Tests\MockClass\OtherStepMock: Tests\MockClass\MessageDataMock
Tests\MockClass\StepMock-->Tests\MockClass\PostStepMock: Tests\MockClass\MessageDataMock
Tests\MockClass\OtherStepMock-->Tests\MockClass\PostStepMock: Tests\MockClass\MessageDataSecondMock
Tests\MockClass\PostStepMock-->[*]: Tests\MockClass\MessageReturnMock
