---
title: flow.workflow.v1 - /workflow/1
theme: neo
---
stateDiagram-v2
[*]-->Tests\MockClass\StubMock: Tests\MockClass\MessageInitMock
Tests\MockClass\StubMock-->Tests\MockClass\NextStubMock: Tests\MockClass\MessageDataMock
Tests\MockClass\StubMock-->Tests\MockClass\OtherStubMock: Tests\MockClass\MessageDataMock
Tests\MockClass\StubMock-->Tests\MockClass\PostStubMock: Tests\MockClass\MessageDataMock
Tests\MockClass\OtherStubMock-->Tests\MockClass\PostStubMock: Tests\MockClass\MessageDataSecondMock
Tests\MockClass\PostStubMock-->[*]: Tests\MockClass\MessageReturnMock
